In [3]:
# Program to create Employee class and perform some actions to print employees count and average salary
class Employee:
    # data member to count the number of Employees
    employee_count = 0

    def __init__(self, name, family, salary, department):
        # instance variables
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department

        # Increment the employee count
        Employee.employee_count += 1 

    
    def average_salary(employees):
        # method to calculate average salary
        total_salary = sum(emp.salary for emp in employees) # total salary of all employees
        return total_salary / len(employees) # average salary

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department, experience):
        # invoke the constructor of the base class
        super().__init__(name, family, salary, department)
        self.experience = experience

# create the instances of Employee class
employee1 = Employee("Akhila", "Akhila Family", 5000, "Finance")
employee2 = Employee("Akhil", "Akhil Family", 10000, "Acounting")

# create the instances of FulltimeEmployee class
fulltime_employee = FulltimeEmployee("Akhi", "Akhi Family", 15000, "IT", 4)

employees = [employee1, employee2, fulltime_employee]
avg_salary = Employee.average_salary(employees)

# Access the properties of Employee and FulltimeEmployee
print("Total number of employees is ", Employee.employee_count)
print("The average salary is ", avg_salary)
print("The fulltime employee name is ", fulltime_employee.name)
print("The experience of fulltime employee is ", fulltime_employee.experience)


Total number of employees is  3
The average salary is  10000.0
The fulltime employee name is  Akhi
The experience of fulltime employee is  4


In [10]:
!pip install numpy

DEPRECATION: Loading egg at /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/jupyter-1.0.0-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 403.2 kB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.7/13.7 MB 41.1 MB/s eta 0:00:0000:0100:01


In [11]:
import numpy as np

In [12]:
# Program to print reshaped array using numpy

# create random vector of size 20 having only float in the range 1-20
random_vector = np.random.uniform(1, 20, size=20) #get the random samples from uniform distribution and returns the random samples as numpy array
print("\nOriginal Random Vector:")
print(random_vector)

reshaped_array = random_vector.reshape(4, 5) # reshape an array to 4X5

max_indices = np.argmax(reshaped_array, axis=1) #replace the max in each row by 0 (axis=1)

reshaped_array[np.arange(4), max_indices] = 0

print("\nReshaped array:")
print(reshaped_array)


Original Random Vector:
[ 9.27518272  6.51435914  1.95075723 15.08262408  4.45038008 19.52009232
 10.49812865 16.7399312   6.51660138  8.35082648  4.42262951 14.06118838
 19.15704679 14.27205003 16.76753692  5.92524498  3.13336461 17.42782801
 14.16094429 12.77282871]

Reshaped array:
[[ 9.27518272  6.51435914  1.95075723  0.          4.45038008]
 [ 0.         10.49812865 16.7399312   6.51660138  8.35082648]
 [ 4.42262951 14.06118838  0.         14.27205003 16.76753692]
 [ 5.92524498  3.13336461  0.         14.16094429 12.77282871]]
